[programs.localnet]
lending_protocol = "EXa8m4H4vavv5fa8CdjMS6eDvSzqXaYWjhMN3fPmyqVh"

[programs.devnet]
lending_protocol = "EXa8m4H4vavv5fa8CdjMS6eDvSzqXaYWjhMN3fPmyqVh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/luissoares/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/**/*.js"
